baseURL = "https://jayanti.justmove.hk"
languageCode = "en-us"
title = "Jayanti"

[params]
  author = "Just Move Limited"
  description = "全手工製作、百分百天然的非一般產品"
  facebooklink = "https://www.facebook.com/jayanti.hk.shop/"
  instgramlink = "https://www.instagram.com/jayanti.organic/"

[[menu.main]]
identifier = "home"
name = "首頁"
url = "/home/home"
weight = 1
[[menu.main]]
identifier = "about"
name = "關於JAYANTI"
url = "/about/about"
weight = 2
[[menu.main]]
identifier = "gdv"
name = "氣能掃描"
url = "/gdv/gdv"
weight = 3
[[menu.main]]
identifier = "product"
name = "產品介紹"
url = "https://justore.jayantihk.com/"
weight = 4
[[menu.main]]
identifier = "contact"
name = "銷售點"
url = "/contact/contact"
weight = 5
[[menu.main]]
identifier = "promotions"
name = "最新優惠"
url = "/promotions"
weight = 6
[[menu.main]]
identifier = "english"
name = "English"
url = "http://www.jayanti.eu/"
weight = 7

