baseURL = "https://jayantihk.com"
languageCode = "en-us"
title = "Jayanti"

[params]
  author = "Just Move Limited"
  description = "全手工製作、百分百天然的非一般產品"
  facebooklink = "https://www.facebook.com/jayanti.hk"
  instgramlink = "https://www.instagram.com/jayanti.organic/"
  youtubelink = "https://www.youtube.com/@jayanti5462"

[[menu.main]]
identifier = "home"
name = "首頁"
url = "/home/home"
weight = 1
[[menu.main]]
identifier = "about"
name = "關於JAYANTI"
url = "/about/about"
weight = 2
[[menu.main]]
identifier = "gdv"
name = "氣能掃描"
url = "/gdv/gdv"
weight = 3
[[menu.main]]
identifier = "product"
name = "產品介紹"
url = "https://product.jayantihk.com/"
weight = 4
[[menu.main]]
identifier = "contact"
name = "公司資料"
url = "/contact/contact"
weight = 5
[[menu.main]]
identifier = "english"
name = "English"
url = "http://www.jayanti.eu/"
weight = 6

